### ISSUE TITLE
Discuss01

### ISSUE THREAD

**Issue by futurefeeling** [gmfe/standard#1]
> Redux 官方的一些建议：

#### **Reducer** 是 `pure function`，这点非常重要，所以绝对不要在 **reducer** 里面做一些引入 `side-effects` 的事情，比如
- 直接修改 state 参数对象
- 请求 API
- 调用不纯的函数，比如 Data.now() Math.random()

#### 唯一改变 `state` 的方法是`触发action`

**Comment by futurefeeling** [comment]
#### 组件的 **Less** 是否应该在组件里面引用呢？

**Comment by liyatang** [comment]
@futurefeeling  这个提议好。基本很少会有组件的less，索性就暴力高效。  就没有做的这么细。 后续如果用了css module 可以采用这种情况。
