### ISSUE TITLE
变量和回调函数命名规范讨论

### ISSUE THREAD

**Issue by farzer** [gmfe/standard#10]
是否要进行该规范？该规范级别？

如果进行该规范，建议变量命名方式为以下：
- be动词(is, are) + 名词
- 名词 + 名词
- 不用短语

回调函数命名：onXXXX

补充：

变量命名举例：

``` js
let isDriver;    // be + noun
let skuName;    // noun + noun
```

不使用短语
~`let nameOfDriver`~

**Comment by liyatang** [comment]
没看懂

**Comment by fondadam** [comment]
let isDriver;    // be + noun    这个变量只有两个值
let skuName;    // noun + noun  这个变量有多个值

是这样吗？

**Comment by futurefeeling** [comment]
@fondadam 嗯
