### ISSUE TITLE
id命名讨论：驼峰 or x-x

### ISSUE THREAD

**Issue by farzer** [gmfe/standard#11]

**Comment by liyatang** [comment]
个人看法，理由是：在IE浏览器下，如果定义了id，则会在window下有个变量保存了相应的引用。   也就是说 <div id="a-b-c"></div> 可以通过 window['a-b-c'] 来访问到这个dom。    所以把id当做一个变量来看待。 既然是变量就遵循变量命名规则。

**Comment by farzer** [comment]
当初变量看
