### ISSUE TITLE
规范是否有级别，比如某些要求做到，否则发红包，某些只是建议？

### ISSUE THREAD

**Issue by liyatang** [gmfe/standard#4]
rt

**Comment by fondadam** [comment]
每个人都按照自己的名字开分支，然后修改push提pr，大家看过后觉得ok或不妥就留言。
定期让其中一个人merge到master。

其他人要与远程同步的话就直接将自己的分支与 matser 同步即可。
这样子的流程如何?

**Comment by liyatang** [comment]
@fondadam 别讨论该issue无关话题，如需要另开issue。
and 你的这些在微信群上已经说过，没仔细看？

**Comment by rock-zhang** [comment]
可以在每一条规范前面标记[强制]、[建议]等标签，说明规范的级别

**Comment by liyatang** [comment]
好的。
