### ISSUE TITLE
JSX代码格式化讨论

### ISSUE THREAD

**Issue by futurefeeling** [gmfe/standard#6]
![image](https://cloud.githubusercontent.com/assets/9881593/17843266/8cb8b7b8-685e-11e6-9ef5-7e1717aac9c5.png)

如上周五提出的问题，是否显得太臃肿了。

周五讨论的方案：如果一行可以显示就一行书写。

但是还是觉得多行的处理方式太臃肿，其实觉得webstorm格式化的处理方案比较好看😢

或者这里改为建议规范？

你们的看法呢？

**Comment by liyatang** [comment]
支持，and 说明下 webstorm 格式化处理方案是什么方案？

**Comment by futurefeeling** [comment]
c52a2433bc11ae2c10bd866deb1388c9d215844b

**Comment by liyatang** [comment]
@futurefeeling  你链接那个pr是想表达？
有想法就提pr呗

**Comment by futurefeeling** [comment]
额，只是当做熟悉下这个链接的功能....忘了删掉了》。。。。

**Comment by liyatang** [comment]
这个功能不错
